require("dotenv").config();
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),bcrypt=require("bcryptjs");
const {pool,query}=require("./database");
const PORT=Number(process.env.PORT)||3100, SECRET=process.env.JWT_SECRET;
if(!SECRET) throw new Error("JWT_SECRET is required");
const b64=v=>Buffer.from(typeof v==="string"?v:JSON.stringify(v)).toString("base64url");
const sig=v=>crypto.createHmac("sha256",SECRET).update(v).digest("base64url");
function token(id){let h=b64({alg:"HS256",typ:"JWT"}),p=b64({sub:String(id),exp:Math.floor(Date.now()/1000)+86400}),d=h+"."+p;return d+"."+sig(d)}
function verify(t){try{let [h,p,s]=String(t||"").split("."),e=sig(h+"."+p);if(!s||s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;let x=JSON.parse(Buffer.from(p,"base64url"));return x.exp*1000>Date.now()?x.sub:null}catch{return null}}
const send=(r,s,d)=>{r.writeHead(s,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});r.end(JSON.stringify(d))};
const body=req=>new Promise(ok=>{let s="";req.on("data",c=>s+=c);req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch{ok({})}})});
async function me(req){let id=verify(String(req.headers.authorization||"").replace(/^Bearer\s+/i,""));if(!id)return null;let r=await query("select id,name,email,role,phone,active from users where id=$1 and active=true",[id]);return r.rows[0]||null}
const allow=(u,...r)=>u&&r.includes(u.role);
async function init(){
 await query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(30) NOT NULL CHECK(role IN('admin','patient','doctor','pharmacy','reception')),phone VARCHAR(30),active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS patients(id BIGSERIAL PRIMARY KEY,user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,patient_code VARCHAR(30) UNIQUE,name VARCHAR(120) NOT NULL,email VARCHAR(255),phone VARCHAR(30),gender VARCHAR(30),date_of_birth DATE,blood_group VARCHAR(10),address TEXT,emergency_contact VARCHAR(120),created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS doctors(id BIGSERIAL PRIMARY KEY,user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,doctor_code VARCHAR(30) UNIQUE,name VARCHAR(120) NOT NULL,specialization VARCHAR(120),phone VARCHAR(30),email VARCHAR(255),created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS appointments(id BIGSERIAL PRIMARY KEY,patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL,appointment_date DATE NOT NULL,appointment_time TIME,reason TEXT,status VARCHAR(30) DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS medicines(id BIGSERIAL PRIMARY KEY,name VARCHAR(160) NOT NULL,generic_name VARCHAR(160),batch_number VARCHAR(100),quantity INTEGER DEFAULT 0,unit_price NUMERIC(12,2) DEFAULT 0,expiry_date DATE,supplier VARCHAR(160),created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS prescriptions(id BIGSERIAL PRIMARY KEY,patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL,appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,notes TEXT,status VARCHAR(30) DEFAULT 'active',created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS medical_records(id BIGSERIAL PRIMARY KEY,patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,doctor_id BIGINT REFERENCES doctors(id),appointment_id BIGINT REFERENCES appointments(id),diagnosis TEXT,symptoms TEXT,treatment TEXT,notes TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS bills(id BIGSERIAL PRIMARY KEY,patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,appointment_id BIGINT REFERENCES appointments(id),amount NUMERIC(12,2) DEFAULT 0,payment_method VARCHAR(30),payment_status VARCHAR(30) DEFAULT 'pending',description TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),paid_at TIMESTAMPTZ);
 CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),action VARCHAR(160) NOT NULL,entity_type VARCHAR(80),entity_id BIGINT,details JSONB,created_at TIMESTAMPTZ DEFAULT NOW());
 ALTER TABLE doctors ADD COLUMN IF NOT EXISTS department VARCHAR(120);
 ALTER TABLE doctors ADD COLUMN IF NOT EXISTS qualification VARCHAR(180);
 ALTER TABLE doctors ADD COLUMN IF NOT EXISTS consultation_fee NUMERIC(12,2) DEFAULT 0;
 ALTER TABLE doctors ADD COLUMN IF NOT EXISTS available_days VARCHAR(180);
 ALTER TABLE doctors ADD COLUMN IF NOT EXISTS available_from TIME;
 ALTER TABLE doctors ADD COLUMN IF NOT EXISTS available_to TIME;`);
 let em=(process.env.ADMIN_EMAIL||"admin@hospital.local").toLowerCase(),pw=process.env.ADMIN_PASSWORD;
 if(pw){let e=await query("select id from users where email=$1",[em]);if(!e.rows.length)await query("insert into users(name,email,password_hash,role) values($1,$2,$3,'admin')",["Hospital Administrator",em,await bcrypt.hash(pw,12)])}
}
async function audit(uid,a,t,id=null,d={}){try{await query("insert into audit_logs(user_id,action,entity_type,entity_id,details) values($1,$2,$3,$4,$5)",[uid,a,t,id,JSON.stringify(d)])}catch{}}
const server=http.createServer(async(req,res)=>{
 let url=new URL(req.url,"http://localhost"),p=url.pathname,m=req.method;
 if(!p.startsWith("/api/")){let base=path.join(__dirname,"public"),f=path.normalize(path.join(base,p==="/"?"/index.html":p));if(!f.startsWith(base)||!fs.existsSync(f)){res.writeHead(404);return res.end("Not found")}res.writeHead(200,{"content-type":f.endsWith(".html")?"text/html; charset=utf-8":"application/octet-stream"});return fs.createReadStream(f).pipe(res)}
 try{
  let b=await body(req);
  if(p==="/api/health"){let x=await query("select current_database() database,now() time");return send(res,200,{ok:true,database:"Neon PostgreSQL",databaseName:x.rows[0].database,time:x.rows[0].time})}
  if(p==="/api/login"&&m==="POST"){let e=String(b.email||"").toLowerCase(),r=await query("select * from users where lower(email)=lower($1) and active=true",[e]),u=r.rows[0];if(!u||!await bcrypt.compare(String(b.password||""),u.password_hash))return send(res,401,{error:"Wrong email or password"});await audit(u.id,"login","users",u.id);return send(res,200,{token:token(u.id),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
  let u=await me(req);if(!u)return send(res,401,{error:"Please sign in again"});
  if(p==="/api/me")return send(res,200,{user:u});
  if(p==="/api/doctors"&&m==="GET"){let r=await query("select d.id,d.user_id,d.doctor_code,d.name,d.specialization,d.department,d.qualification,d.consultation_fee,d.available_days,d.available_from,d.available_to,d.email,d.phone,coalesce(u.active,true) active from doctors d left join users u on u.id=d.user_id where u.active=true or d.user_id is null order by d.name");return send(res,200,r.rows)}
  if(p==="/api/doctors"&&m==="POST"){if(!allow(u,"admin"))return send(res,403,{error:"Access denied"});if(!b.name||!b.email||String(b.password||"").length<8)return send(res,400,{error:"Name, email and password (8+ chars) required"});let c=await pool.connect();try{await c.query("begin");let h=await bcrypt.hash(b.password,12),ur=await c.query("insert into users(name,email,password_hash,role,phone) values($1,$2,$3,'doctor',$4) returning id,name,email,phone",[b.name,String(b.email).toLowerCase(),h,b.phone||null]),x=ur.rows[0];let dr=await c.query("insert into doctors(user_id,doctor_code,name,specialization,phone,email,department,qualification,consultation_fee,available_days,available_from,available_to) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *",[x.id,"DOC-"+String(x.id).padStart(5,"0"),x.name,b.specialization||null,x.phone,x.email,b.department||null,b.qualification||null,+b.consultation_fee||0,b.available_days||null,b.available_from||null,b.available_to||null]);await c.query("commit");await audit(u.id,"create","doctors",dr.rows[0].id,{email:x.email});return send(res,201,dr.rows[0])}catch(e){await c.query("rollback");throw e}finally{c.release()}}
  if(p==="/api/stats"){if(!allow(u,"admin"))return send(res,403,{error:"Access denied"});let r=await query(`select (select count(*) from patients)::int patients,(select count(*) from appointments where appointment_date=current_date and status<>'cancelled')::int today,(select count(*) from doctors)::int doctors,(select coalesce(sum(amount),0) from bills where payment_status='paid') revenue,(select count(*) from bills where payment_status='pending')::int unpaid,(select count(*) from medicines where quantity<=10)::int low,(select count(*) from medicines where expiry_date<=current_date+interval '90 days')::int expiring`);return send(res,200,r.rows[0])}
  if(p==="/api/users"&&m==="GET"){if(!allow(u,"admin"))return send(res,403,{error:"Access denied"});let r=await query("select id,name,email,role,phone,active,created_at from users order by created_at desc");return send(res,200,r.rows)}
  if(p==="/api/users"&&m==="POST"){if(!allow(u,"admin"))return send(res,403,{error:"Access denied"});let role=String(b.role||"").toLowerCase();if(role==="pharmacist")role="pharmacy";if(!["admin","patient","doctor","pharmacy","reception"].includes(role)||!b.name||!b.email||String(b.password||"").length<8)return send(res,400,{error:"Name, email, role and password (8+ chars) required"});let h=await bcrypt.hash(b.password,12),r=await query("insert into users(name,email,password_hash,role,phone) values($1,$2,$3,$4,$5) returning id,name,email,role,phone,active",[b.name,String(b.email).toLowerCase(),h,role,b.phone||null]),x=r.rows[0];if(role==="patient")await query("insert into patients(user_id,patient_code,name,email,phone) values($1,$2,$3,$4,$5)",[x.id,"PAT-"+String(x.id).padStart(5,"0"),x.name,x.email,x.phone]);if(role==="doctor")await query("insert into doctors(user_id,doctor_code,name,email,phone,specialization) values($1,$2,$3,$4,$5,$6)",[x.id,"DOC-"+String(x.id).padStart(5,"0"),x.name,x.email,x.phone,b.specialization||null]);await audit(u.id,"create","users",x.id,{role});return send(res,201,x)}
  let um=p.match(/^\/api\/users\/(\d+)\/(toggle|password)$/);
  if(um&&m==="PATCH"){if(!allow(u,"admin"))return send(res,403,{error:"Access denied"});let id=Number(um[1]);if(id===Number(u.id)&&um[2]==="toggle")return send(res,400,{error:"You cannot deactivate your own account"});if(um[2]==="toggle"){let r=await query("update users set active=not active,updated_at=now() where id=$1 returning id,name,email,role,active",[id]);if(!r.rows.length)return send(res,404,{error:"Account not found"});await audit(u.id,"toggle_account","users",id,{active:r.rows[0].active});return send(res,200,r.rows[0])}if(String(b.password||"").length<8)return send(res,400,{error:"New password must be at least 8 characters"});let h=await bcrypt.hash(b.password,12);let r=await query("update users set password_hash=$1,updated_at=now() where id=$2 returning id,name,email,role,active",[h,id]);if(!r.rows.length)return send(res,404,{error:"Account not found"});await audit(u.id,"reset_password","users",id);return send(res,200,{ok:true})}
  if(p==="/api/patients"&&m==="GET"){let r=u.role==="patient"?await query("select * from patients where user_id=$1",[u.id]):await query("select * from patients order by created_at desc");return send(res,200,r.rows)}
  if(p==="/api/patients"&&m==="POST"){if(!allow(u,"admin","reception"))return send(res,403,{error:"Access denied"});let r=await query("insert into patients(patient_code,name,email,phone,gender,date_of_birth,blood_group,address,emergency_contact) values('PAT-'||to_char(nextval('patients_id_seq'),'FM00000'),$1,$2,$3,$4,$5,$6,$7,$8) returning *",[b.name,b.email||null,b.phone||null,b.gender||null,b.date_of_birth||null,b.blood_group||null,b.address||null,b.emergency_contact||null]);return send(res,201,r.rows[0])}
  if(p==="/api/appointments"&&m==="GET"){let q=`select a.*,p.name patient_name,d.name doctor_name from appointments a join patients p on p.id=a.patient_id left join doctors d on d.id=a.doctor_id`,a=[];if(u.role==="patient"){q+=" where p.user_id=$1";a=[u.id]}else if(u.role==="doctor"){q+=" where d.user_id=$1";a=[u.id]}q+=" order by appointment_date desc,appointment_time desc";return send(res,200,(await query(q,a)).rows)}
  if(p==="/api/appointments"&&m==="POST"){if(!allow(u,"admin","reception","patient"))return send(res,403,{error:"Access denied"});let pid=b.patient_id||b.patientId;if(u.role==="patient"){let z=await query("select id from patients where user_id=$1",[u.id]);pid=z.rows[0]?.id}let r=await query("insert into appointments(patient_id,doctor_id,appointment_date,appointment_time,reason,status) values($1,$2,$3,$4,$5,$6) returning *",[pid,b.doctor_id||b.doctorId,b.appointment_date||b.date,b.appointment_time||b.time,b.reason||null,b.status||"pending"]);return send(res,201,r.rows[0])}
  if(p==="/api/medicines"&&m==="GET")return send(res,200,(await query("select * from medicines order by name")).rows);
  if(p==="/api/medicines"&&m==="POST"){if(!allow(u,"admin","pharmacy"))return send(res,403,{error:"Access denied"});let r=await query("insert into medicines(name,generic_name,batch_number,quantity,unit_price,expiry_date,supplier) values($1,$2,$3,$4,$5,$6,$7) returning *",[b.name,b.generic_name||null,b.batch_number||null,+b.quantity||0,+b.unit_price||0,b.expiry_date||null,b.supplier||null]);return send(res,201,r.rows[0])}
  if(p==="/api/prescriptions"&&m==="GET"){let q=`select pr.*,p.name patient_name,d.name doctor_name from prescriptions pr join patients p on p.id=pr.patient_id left join doctors d on d.id=pr.doctor_id`,a=[];if(u.role==="patient"){q+=" where p.user_id=$1";a=[u.id]}return send(res,200,(await query(q+" order by pr.created_at desc",a)).rows)}
  if(p==="/api/records"&&m==="GET"){let q=`select mr.*,p.name patient_name,d.name doctor_name from medical_records mr join patients p on p.id=mr.patient_id left join doctors d on d.id=mr.doctor_id`,a=[];if(u.role==="patient"){q+=" where p.user_id=$1";a=[u.id]}return send(res,200,(await query(q+" order by mr.created_at desc",a)).rows)}
  if(p==="/api/bills"&&m==="GET"){let q=`select b.*,p.name patient_name from bills b join patients p on p.id=b.patient_id`,a=[];if(u.role==="patient"){q+=" where p.user_id=$1";a=[u.id]}return send(res,200,(await query(q+" order by b.created_at desc",a)).rows)}
  if(p==="/api/audit"&&m==="GET"){if(!allow(u,"admin"))return send(res,403,{error:"Access denied"});return send(res,200,(await query("select a.*,coalesce(u.name,'System') user_name from audit_logs a left join users u on u.id=a.user_id order by a.created_at desc limit 100")).rows)}
  return send(res,404,{error:"API route not found"});
 }catch(e){console.error(e);return send(res,500,{error:e.code==="23505"?"That email/code already exists":"Server error"})}
});
init().then(()=>server.listen(PORT,"0.0.0.0",()=>console.log(`MediCare HMS running: http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
process.on("SIGTERM",()=>server.close(async()=>{await pool.end();process.exit(0)}));
