// Checkpoint tests. Start the server first (fresh data folder recommended), then: node test.js
const B='http://localhost:'+(process.env.PORT||3100)+'/api/';let ok=0,bad=0;
const t=(n,c)=>{c?ok++:bad++;console.log((c?'PASS ':'FAIL ')+n)};
const call=async(p,m='GET',b,k)=>{const r=await fetch(B+p,{method:m,headers:{'content-type':'application/json',...(k?{authorization:'Bearer '+k}:{})},body:b?JSON.stringify(b):undefined});return{s:r.status,j:await r.json().catch(()=>({}))}};
const L=async(e,p)=>(await call('login','POST',{email:e+'@hospital.local',password:p})).j.token;
(async()=>{
const A=await L('admin','Admin@123'),D=await L('doctor','Doctor@123'),R=await L('reception','Reception@123'),P=await L('pharmacy','Pharma@123');
t('CP1 all 4 roles log in',!!(A&&D&&R&&P));
t('CP1 wrong password rejected',(await call('login','POST',{email:'admin@hospital.local',password:'x'})).s===401);
t('CP1 no token rejected',(await call('patients')).s===401);
t('CP1 reception cannot read records',(await call('records','GET',0,R)).s===403);
t('CP1 pharmacist cannot read patients',(await call('patients','GET',0,P)).s===403);
t('CP2 bad phone rejected',(await call('patients','POST',{name:'A',age:30,phone:'123'},R)).s===400);
const pt=(await call('patients','POST',{name:'Ravi',age:34,gender:'Male',phone:'9876543210'},R)).j;t('CP2 patient created',!!pt.id);
const dr=(await call('doctors','GET',0,R)).j[0],tm='10:'+String(Math.floor(Math.random()*60)).padStart(2,'0');
const ap={patientId:pt.id,doctor:dr.id,date:'2030-01-01',time:tm};
const a1=(await call('appointments','POST',ap,R));t('CP3 appointment booked',a1.s===200);
t('CP3 double booking blocked',(await call('appointments','POST',ap,R)).s===400);
await call('appointments/'+a1.j.id,'PUT',{status:'Cancelled'},R);t('CP3 cancel frees the slot',(await call('appointments','POST',ap,R)).s===200);
t('CP3 doctor sees own appointments',(await call('appointments','GET',0,D)).j.length>=1);
const med=(await call('medicines','GET',0,P)).j.find(m=>m.name.startsWith('Paracetamol'));
t('CP4 receptionist cannot write record',(await call('records','POST',{patientId:pt.id,diagnosis:'Fever'},R)).s===403);
const rec=(await call('records','POST',{patientId:pt.id,diagnosis:'Fever',treatment:'Rest',medicineId:med.id,qty:10},D)).j;t('CP4 doctor writes record',!!rec.id);
t('CP5 dispense ok',(await call('dispense','POST',{id:rec.id},P)).s===200);
t('CP5 stock reduced by 10',(await call('medicines','GET',0,P)).j.find(m=>m.id===med.id).stock===med.stock-10);
t('CP5 double dispense blocked',(await call('dispense','POST',{id:rec.id},P)).s===409);
const big=(await call('records','POST',{patientId:pt.id,diagnosis:'X',medicineId:med.id,qty:99999},D)).j;
t('CP5 insufficient stock blocked',(await call('dispense','POST',{id:big.id},P)).s===409);
const bl=(await call('bills','POST',{patientId:pt.id,consultation:500,medicine:100,other:0,discount:100,taxPct:10,status:'Unpaid'},R)).j;t('CP6 bill total correct (550)',bl.total===550);
await call('bills/'+bl.id,'PUT',{status:'Paid'},R);
t('CP6 paid bill locked',(await call('bills/'+bl.id,'PUT',{other:5},R)).s===409);
const st=(await call('stats','GET',0,A)).j;t('CP7 dashboard revenue includes 550',st.revenue>=550);
t('CP7 non-admin blocked from stats',(await call('stats','GET',0,R)).s===403);
const nu=(await call('users','POST',{name:'Temp',email:'tmp@hospital.local',role:'doctor',password:'Temp@1234'},A)).j;
const tk=await L('tmp','Temp@1234');t('CP7 new staff can log in',!!tk);
await call('users/'+nu.id,'PUT',{active:'false'},A);t('CP7 disabled staff blocked immediately',(await call('patients','GET',0,tk)).s===401);
t('CP8 XSS-style input stored safely (no crash)',(await call('patients','POST',{name:'<img src=x onerror=1>',age:20,phone:'9876543211'},R)).s===200);
t('CP8 malformed JSON handled',(await call('patients','POST',undefined,R)).s===400);
console.log(`\n${ok} passed, ${bad} failed`);process.exit(bad?1:0)})();
